onboarding = false
[theme]
name = "terminal"
auto_switch = true
dark_name = "catppuccin"
light_name = "catppuccin-latte"

[ui.toast]
delivery = "system"

[keys]
prefix = "ctrl+a"

[[keys.command]]
key = "prefix+ctrl+y"
type = "popup"
command = "yazi"
description = "run yazi"
width = "85%"
height = "85%"

[[keys.command]]
key = "prefix+ctrl+g"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "85%"
height = "85%"

[[keys.command]]
key = "prefix+ctrl+t"
type = "popup"
command = "exec zsh"
description = "open scratch terminal"
width = "85%"
height = "85%"

[ui]
agent_panel_sort = "spaces"
