onboarding = false
[theme]
name = "terminal"
auto_switch = true
dark_name = "catppuccin"
light_name = "catppuccin-latte"

[ui.toast]
delivery = "system"

[keys]
prefix = "ctrl+a"

[[keys.command]]
key = "prefix+alt+g"
type = "pane"
command = "lazygit"
description = "run lazygit"

[ui]
agent_panel_sort = "spaces"
