{
  config,
  pkgs,
  lib,
  username,
  unstable,
  ...
}:
let
  dotfiles = "${config.home.homeDirectory}/dotfiles";
  link = path: config.lib.file.mkOutOfStoreSymlink "${dotfiles}/${path}";
in
{
  home = {
    inherit username;
    homeDirectory = "/Users/${username}";
    stateVersion = "25.11";
  };

  home.packages = with pkgs; [
    # Shell utilities
    home-manager
    carapace
    direnv
    zoxide
    zsh-abbr
    zsh-autosuggestions
    zsh-completions
    zsh-fast-syntax-highlighting
    starship

    # File operations
    bat
    dust
    eza
    fd
    fzf
    ripgrep

    # Text / data
    difftastic

    # Dev tools
    neovim
    tree-sitter
    just

    # AI Coding Agent
    claude-code
    unstable.codex
    unstable.github-copilot-cli

    # General Formatters
    autocorrect
    dprint
    # prettierd: used for markdown because dprint-plugin-markdown hardcodes 2-space list indent.
    # tabWidth:4 in ~/.prettierrc gives 4-space list nesting to match Obsidian.
    # TODO: replace with dprint once https://github.com/dprint/dprint-plugin-markdown/pull/176 merges.
    prettierd

    # Nix tools
    nixd
    nixfmt-rfc-style
    statix
    deadnix
    vulnix

    # Python tools
    uv

    # Rust tools
    rustup

    # TypeScript tools
    nodejs
    pnpm
    nodePackages."@antfu/ni"

    # Lua tools
    stylua
    selene
    lua-language-server

    # LaTeX tools
    texlab
    tex-fmt
    ltex-ls

    # macOS-specific
    mas
    xcodes
    dotenvx
    marp-cli
  ];

  # Zsh plugin file generated by Nix（case B: .zshrc stays as dotfile symlink）
  # ${pkgs.xxx} is expanded to /nix/store/... at evaluation time
  home.file.".config/zsh/nix-plugins.zsh".text = ''
    source ${pkgs.zsh-autosuggestions}/share/zsh-autosuggestions/zsh-autosuggestions.zsh
    source ${pkgs.zsh-fast-syntax-highlighting}/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
    source ${pkgs.zsh-abbr}/share/zsh/zsh-abbr/zsh-abbr.zsh
  '';

  programs = {
    git = {
      enable = true;
      settings = {
        user.name = "furedea";
        user.email = "132188853+furedea@users.noreply.github.com";
        init.defaultBranch = "main";
        credential.helper = "osxkeychain";
        column.ui = "auto";
        branch.sort = "-committerdate";
        tag.sort = "version:refname";
        diff = {
          algorithm = "histogram";
          colorMoved = "plain";
          mnemonicPrefix = true;
          renames = true;
          external = "difft";
        };
        push = {
          default = "simple";
          autoSetupRemote = true;
          followTags = true;
        };
        fetch = {
          prune = true;
          pruneTags = true;
          all = true;
        };
        help.autocorrect = "prompt";
        commit.verbose = true;
        rerere = {
          enabled = true;
          autoupdate = true;
        };
        core = {
          excludesfile = "~/.gitignore";
          fsmonitor = true;
          untrackedCache = true;
        };
        rebase = {
          autoSquash = true;
          autoStash = true;
          updateRefs = true;
        };
        merge.conflictstyle = "zdiff3";
      };
    };

    delta = {
      enable = true;
      enableGitIntegration = true;
    };

    jujutsu = {
      enable = true;
      settings = {
        user.name = "furedea";
        user.email = "132188853+furedea@users.noreply.github.com";
        ui = {
          "diff-editor" = ":builtin";
          "diff.tool" = [
            "difft"
            "--color=always"
            "$left"
            "$right"
          ];
          pager = "less -FRX";
        };
      };
    };

    gh = {
      enable = true;
      settings = {
        git_protocol = "https";
        prompt = "enabled";
        aliases.co = "pr checkout";
      };
    };

    direnv = {
      enable = true;
      enableZshIntegration = false; # .zshrc is a dotfile symlink; hook manually there
      nix-direnv.enable = true;
    };

    atuin = {
      enable = true;
      package = unstable.atuin;
      enableZshIntegration = false; # .zshrc が dotfile のため手動 eval を使う
      settings = {
        enter_accept = true;
        sync.records = true;
      };
    };

    yazi = {
      enable = true;
      settings = {
        mgr.show_hidden = true;
      };
      keymap = {
        mgr.prepend_keymap = [
          {
            on = [ "o" ];
            run = "create";
            desc = "Create a file or directory";
          }
          {
            on = [ "<Esc>" ];
            run = "quit";
            desc = "Quit";
          }
        ];
      };
    };

    tmux = {
      enable = true;
      mouse = true;
      extraConfig = ''
        set -s extended-keys on
        set -as terminal-features 'xterm-ghostty:extkeys'

        # vim-tmux-navigator
        is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
        bind-key -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
        bind-key -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
        bind-key -n C-k if-shell "$is_vim" "send-keys C-k" "if -F '#{pane_at_top}' 'send-keys C-k' 'select-pane -U'"
        bind-key -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"

        # Dim inactive panes (Catppuccin Mocha)
        set -g window-style 'fg=#6c7086,bg=#181825'
        set -g window-active-style 'fg=#cdd6f4,bg=#1e1e2e'
      '';
    };
  };

  home.activation = {
    rustupInit = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      ${pkgs.rustup}/bin/rustup toolchain install stable --no-self-update 2>/dev/null || true
    '';
    uvPythonInstall = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      ${pkgs.uv}/bin/uv python install 2>/dev/null || true
    '';
  };

  home.file = {
    # Zsh（dotfileに実ファイル，直接編集可能）
    ".zshrc".source = link "zsh/.zshrc";
    ".zshenv".source = link "zsh/.zshenv";
    ".zprofile".source = link "zsh/.zprofile";

    # Bash
    ".bashrc".source = link "bash/.bashrc";

    # Git ignore
    ".config/git/ignore".source = link "git/ignore";

    # Neovim（多ファイル・頻繁に編集）
    ".config/nvim".source = link "nvim";

    # Starship
    ".config/starship.toml".source = link "starship/starship.toml";
    ".config/starship/jj_prompt.sh".source = link "starship/jj_prompt.sh";

    # Vim
    ".vimrc".source = link "vim/.vimrc";

    # dprint (global formatter config — dprint looks for ~/dprint.json by default)
    "dprint.json".source = link "dprint/dprint.json";

    # prettierd (global formatter config)
    ".prettierrc".source = link "prettier/.prettierrc";

    # macOS GUI 設定
    ".config/ghostty/config".source = link "ghostty/config";
    ".config/karabiner/karabiner.json".source = link "karabiner/karabiner.json";
    # Codex (shares the same global instructions and skills as Claude Code)
    ".codex/AGENTS.md".source = link "claude/CLAUDE.md";
    ".codex/skills".source = link "claude/skills";

    # Claude Code
    ".claude/agents".source = link "claude/agents";
    ".claude/commands".source = link "claude/commands";
    ".claude/hooks".source = link "claude/hooks";
    ".claude/statuslines".source = link "claude/statuslines";
    ".claude/skills".source = link "claude/skills";
    ".claude/rules".source = link "claude/rules";
    ".claude/CLAUDE.md".source = link "claude/CLAUDE.md";
    ".claude/settings.json".source = link "claude/settings.json";
  };
}
