{
  config,
  pkgs,
  lib,
  username,
  dotfilesDir,
  unstable,
  nix-claude-code,
  codex-cli-nix,
  system,
  ...
}:
let
  link = path: config.lib.file.mkOutOfStoreSymlink "${dotfilesDir}/${path}";
in
{
  home = {
    inherit username;
    homeDirectory = "/Users/${username}";
    stateVersion = "25.11";
  };

  home.packages = with pkgs; [
    # Shell utilities
    home-manager
    carapace
    direnv
    zoxide
    zsh-abbr
    zsh-autosuggestions
    zsh-completions
    zsh-fast-syntax-highlighting
    starship

    # File operations
    bat
    dust
    eza
    fd
    fzf
    ripgrep

    # Dev tools
    neovim
    tree-sitter
    just
    actionlint
    lefthook
    commitlint
    ghq
    roots
    git-wt

    # AI Coding Agent
    nix-claude-code.packages.${system}.default
    codex-cli-nix.packages.${system}.default
    unstable.github-copilot-cli
    unstable.opencode

    # General Formatters
    autocorrect
    dprint
    # prettierd: used for markdown because dprint-plugin-markdown hardcodes 2-space list indent.
    # tabWidth:4 in ~/.prettierrc gives 4-space list nesting to match Obsidian.
    # TODO: replace with dprint once https://github.com/dprint/dprint-plugin-markdown/pull/176 merges.
    prettierd

    # Nix tools
    nixd
    nixfmt-rfc-style
    statix
    deadnix
    vulnix

    # ShellScript tools(bash)
    shellcheck
    shfmt
    bash-language-server
    bats

    # Python tools
    uv

    # Rust tools
    rustup

    # TypeScript tools
    nodejs
    pnpm
    nodePackages."@antfu/ni"
    typescript
    typescript-language-server
    unstable.oxfmt
    unstable.oxlint
    unstable.tsgolint

    # Lua tools
    stylua
    selene
    lua-language-server

    # LaTeX tools
    texlab
    tex-fmt
    ltex-ls

    # macOS-specific
    xcodes
    dotenvx
    marp-cli
  ];

  # Zsh plugin file generated by Nix（case B: .zshrc stays as dotfile symlink）
  # ${pkgs.xxx} is expanded to /nix/store/... at evaluation time
  home.file.".config/zsh/nix-plugins.zsh".text = ''
    source ${pkgs.zsh-autosuggestions}/share/zsh-autosuggestions/zsh-autosuggestions.zsh
    source ${pkgs.zsh-fast-syntax-highlighting}/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
    source ${pkgs.zsh-abbr}/share/zsh/zsh-abbr/zsh-abbr.zsh
  '';

  programs = {
    git = {
      enable = true;
      settings = {
        user = {
          name = "furedea";
          email = "132188853+furedea@users.noreply.github.com";
          signingkey = "~/.ssh/id_ed25519.pub";
        };
        gpg.format = "ssh";
        commit.gpgsign = true;
        tag.gpgsign = true;
        init.defaultBranch = "main";
        credential.helper = "osxkeychain";
        column.ui = "auto";
        branch.sort = "-committerdate";
        tag.sort = "version:refname";
        diff = {
          algorithm = "histogram";
          colorMoved = "plain";
          mnemonicPrefix = true;
          renames = true;
        };
        pull.rebase = true;
        push = {
          default = "simple";
          autoSetupRemote = true;
          followTags = true;
        };
        fetch = {
          prune = true;
          pruneTags = true;
          all = true;
        };
        help.autocorrect = "prompt";
        commit.verbose = true;
        rerere = {
          enabled = true;
          autoupdate = true;
        };
        core = {
          fsmonitor = true;
          untrackedCache = true;
        };
        rebase = {
          autoSquash = true;
          autoStash = true;
          updateRefs = true;
        };
        merge.conflictstyle = "zdiff3";
        transfer.fsckObjects = true;
        fetch.fsckObjects = true;
        receive.fsckObjects = true;
        status.short = true;
        status.branch = true;
        alias.cc = "!f() { tmpf=$(mktemp) && codex exec --full-auto -o \"$tmpf\" 'Review the staged diff and generate a Conventional Commits message. Output ONLY the commit message, nothing else.' && git commit -F \"$tmpf\"; rm -f \"$tmpf\"; }; f";
        alias.wtd = "wt -D";
      };
    };

    delta = {
      enable = true;
      enableGitIntegration = true;
      options = {
        side-by-side = true;
        navigate = true;
        hyperlinks = true;
        true-color = "always";
        syntax-theme = "ansi";
        line-numbers = true;
        features = "decorations unobtrusive-line-numbers";
        plus-style = "#a6e3a1";
        plus-emph-style = "bold #a6e3a1";
        minus-style = "#f38ba8";
        minus-emph-style = "bold #f38ba8";
        zero-style = "normal";
        hunk-header-style = "bold #89b4fa";
        decorations = {
          commit-decoration-style = "bold #f9e2af box ul";
          file-style = "bold #89b4fa ul";
          file-decoration-style = "none";
          hunk-header-decoration-style = "#94e2d5 box ul";
        };
        unobtrusive-line-numbers = {
          line-numbers-left-format = "{nm:>4}┊";
          line-numbers-right-format = "{np:>4}│";
          line-numbers-left-style = "#6c7086";
          line-numbers-right-style = "#6c7086";
          line-numbers-minus-style = "#6c7086";
          line-numbers-zero-style = "#6c7086";
          line-numbers-plus-style = "#6c7086";
        };
      };
    };

    gh = {
      enable = true;
      settings = {
        git_protocol = "https";
        prompt = "enabled";
        aliases.co = "pr checkout";
      };
    };

    gh-dash = {
      enable = true;
      settings = {
        defaults.refetchIntervalMinutes = 5;
        keybindings.prs = [
          {
            key = "m";
            command = "gh pr merge --squash --auto -d {{.PrNumber}} -R {{.RepoName}}";
          }
        ];
      };
    };

    lazygit = {
      enable = true;
      settings = {
        gui = {
          nerdFontsVersion = "3";
          showIcons = true;
          expandFocusedSidePanel = true;
          showRandomTip = false;
        };
        git = {
          pagers = [
            {
              colorArg = "always";
              pager = "delta --paging=never";
            }
          ];
          branchLogCmd = "git log --graph --color=always --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' {{branchName}} --";
          allBranchesLogCmds = [
            "git log --graph --color=always --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --all"
          ];
        };
        customCommands = [
          {
            key = "C";
            command = ''npx --yes --package czg@1.13.0 --package @commitlint/config-conventional --call 'NODE_PATH="$(dirname "$(dirname "$(command -v czg)")")''${NODE_PATH:+:$NODE_PATH}" czg' '';
            context = "files";
            loadingText = "Opening czg";
            output = "terminal";
          }
        ];
      };
    };

    direnv = {
      enable = true;
      enableZshIntegration = false; # .zshrc is a dotfile symlink; hook manually there
      nix-direnv.enable = true;
    };

    atuin = {
      enable = true;
      package = unstable.atuin;
      enableZshIntegration = false; # .zshrc が dotfile のため手動 eval を使う
      settings = {
        enter_accept = true;
        sync.records = true;
      };
    };

    yazi = {
      enable = true;
      settings = {
        mgr.show_hidden = true;
      };
      keymap = {
        mgr.prepend_keymap = [
          {
            on = [ "o" ];
            run = "create";
            desc = "Create a file or directory";
          }
          {
            on = [ "<Esc>" ];
            run = "quit";
            desc = "Quit";
          }
        ];
      };
    };

    tmux = {
      enable = true;
      mouse = true;
      extraConfig = ''
        set -s extended-keys on
        set -as terminal-features 'xterm-ghostty:extkeys'

        # vim-tmux-navigator
        is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
        bind-key -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
        bind-key -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
        bind-key -n C-k if-shell "$is_vim" "send-keys C-k" "if -F '#{pane_at_top}' 'send-keys C-k' 'select-pane -U'"
        bind-key -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"

        # Dim inactive panes (Catppuccin Mocha)
        set -g window-style 'fg=#6c7086,bg=#181825'
        set -g window-active-style 'fg=#cdd6f4,bg=#1e1e2e'
      '';
    };
  };

  home.activation = {
    rustupInit = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      ${pkgs.rustup}/bin/rustup toolchain install stable --no-self-update 2>/dev/null || true
    '';
    uvPythonInstall = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      ${pkgs.uv}/bin/uv python install 2>/dev/null || true
    '';
    sshKeyGen = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      if [ ! -f ~/.ssh/id_ed25519 ]; then
        mkdir -p ~/.ssh
        ssh-keygen -t ed25519 -C "132188853+furedea@users.noreply.github.com" -f ~/.ssh/id_ed25519 -N ""
      fi
    '';
  };

  # lazygit reads XDG_CONFIG_HOME/lazygit/config.yml first when XDG_CONFIG_HOME is set
  # in the shell, but home-manager writes to ~/Library/Application Support/lazygit/ on macOS.
  # Mirror to the XDG path so the home-manager-generated config is actually used.
  xdg.configFile."lazygit/config.yml".source =
    config.home.file."Library/Application Support/lazygit/config.yml".source;

  home.file = {
    # Zsh（dotfileに実ファイル，直接編集可能）
    ".zshrc".source = link "zsh/.zshrc";
    ".zshenv".source = link "zsh/.zshenv";
    ".zprofile".source = link "zsh/.zprofile";

    # Bash
    ".bashrc".source = link "bash/.bashrc";

    # Git ignore
    ".config/git/ignore".source = link "git/ignore";

    # Neovim（多ファイル・頻繁に編集）
    ".config/nvim".source = link "nvim";

    # Starship
    ".config/starship.toml".source = link "starship/starship.toml";

    # Vim
    ".vimrc".source = link "vim/.vimrc";

    # dprint (global formatter config — dprint looks for ~/dprint.json by default)
    "dprint.json".source = link "dprint/dprint.json";

    # prettierd (global formatter config)
    ".prettierrc".source = link "prettier/.prettierrc";

    # EditorConfig (global fallback for projects without their own)
    ".editorconfig".source = link ".editorconfig";

    # macOS GUI 設定
    ".config/ghostty/config".source = link "ghostty/config";
    ".config/karabiner/karabiner.json".source = link "karabiner/karabiner.json";
    ".config/cmux/settings.json".source = link "cmux/settings.json";
    # Codex (shares the same global instructions and skills as Claude Code)
    ".codex/AGENTS.md".source = link "claude/CLAUDE.md";
    ".codex/skills".source = link "claude/skills";
    ".codex/hooks".source = link "codex/hooks";
    ".codex/hooks.json".source = link "codex/hooks.json";

    # Claude Code
    ".claude/agents".source = link "claude/agents";
    ".claude/commands".source = link "claude/commands";
    ".claude/hooks".source = link "claude/hooks";
    ".claude/statusline".source = link "claude/statusline";
    ".claude/skills".source = link "claude/skills";
    ".claude/CLAUDE.md".source = link "claude/CLAUDE.md";
    ".claude/settings.json".source = link "claude/settings.json";
  };
}
