ls:
  .dir: regex:\.?[a-z0-9]+(-[a-z0-9]+)*
  .*: regex:[a-z0-9]*([._][a-z0-9]+)*

ignore:
  - .git
  - .direnv
  - result
  - result-*
  - "**/logs"
  - "**/.cache"

  - "**/README.md"
  - "**/AGENTS.md"
  - "**/CLAUDE.md"
  - "**/SKILL.md"

  - .venv
  - .uv-cache
  - .ruff_cache
  - .pytest_cache
  - .ipynb_checkpoints
  - "**/__pycache__"
  - "**/__init__.py"
  - dist
  - build

  - "raycast/Raycast 2026-04-15 14.52.13.rayconfig"
